-- DROP DATABASE bikeshop;
CREATE DATABASE bikeshop;

USE bikeshop;

CREATE TABLE Manufacturer (
    MANUFACTURERID INT NOT NULL PRIMARY KEY,
    MANUFACTURERNAME VARCHAR(255),
    CONTACTNAME VARCHAR(100),
    PHONE VARCHAR(20),
    ADDRESS VARCHAR(255),
    ZIPCODE VARCHAR(10),
    CITYID INT,
    BALANCEDUE DECIMAL(10,2)
);

CREATE TABLE Letterstyle (
    LETTERSTYLE VARCHAR(20) NOT NULL PRIMARY KEY,
    DESCRIPTION TEXT
);

CREATE TABLE Component (
    COMPONENTID INT NOT NULL PRIMARY KEY,
    MANUFACTURERID INT NOT NULL,
    PRODUCTNUMBER VARCHAR(50),
    ROAD VARCHAR(20),
    CATEGORY VARCHAR(50),
    LENGTH INT,
    HEIGHT DECIMAL(10,2),
    WIDTH DECIMAL(10,2),
    WEIGHT INT,
    YEAR INT,
    ENDYEAR INT,
    DESCRIPTION TEXT,
    LISTPRICE INT,
    ESTIMATEDCOST DECIMAL(10,2),
    QUANTITYONHAND INT,
    FOREIGN KEY (MANUFACTURERID) REFERENCES Manufacturer(MANUFACTURERID)
);

CREATE TABLE Modeltype (
    MODELTYPE VARCHAR(20) NOT NULL PRIMARY KEY,
    DESCRIPTION VARCHAR(100),
    COMPONENTID INT,
    FOREIGN KEY (COMPONENTID) REFERENCES Component(COMPONENTID)
);

CREATE TABLE Paint (
    PAINTID INT NOT NULL PRIMARY KEY,
    COLORNAME VARCHAR(50),
    COLORSTYLE VARCHAR(50),
    COLORLIST VARCHAR(50),
    DATEINTRODUCED DATE NOT NULL,
    DATEDISCONTINUED DATE
);

CREATE TABLE Tubematerial (
    TUBEID INT NOT NULL PRIMARY KEY,
    MATERIAL VARCHAR(50),
    DESCRIPTION TEXT,
    DIAMETER DECIMAL(10,2),
    THICKNESS INT,
    ROUNDNESS VARCHAR(20),
    WEIGHT DECIMAL(10,2),
    STIFFNESS INT,
    LISTPRICE DECIMAL(10,2),
    CONSTRUCTION VARCHAR(50)
);

CREATE TABLE Bicycle (
    SERIALNUMBER INT NOT NULL PRIMARY KEY,
    CUSTOMERID INT,
    MODELTYPE VARCHAR(20) NOT NULL,
    PAINTID INT NOT NULL,
    FRAMESIZE INT,
    ORDERDATE DATE,
    STARTDATE DATE,
    SHIPDATE DATE,
    SHIPEMPLOYEE INT,
    FRAMEASSEMBLER INT,
    PAINTER INT,
    CONSTRUCTION TEXT,
    WATERBOTTLEBRAZEONS INT,
    CUSTOMNAME VARCHAR(255),
    LETTERSTYLEID VARCHAR(20),
    STOREID INT,
    EMPLOYEEID INT,
    TOPTUBE DECIMAL(10,2),
    CHAINSTAY DECIMAL(10,2),
    HEADTUBEANGLE DECIMAL(10,2),
    SEATTUBEANGLE DECIMAL(10,2),
    LISTPRICE DECIMAL(10,2),
    SALEPRICE DECIMAL(10,2),
    SALESTAX DECIMAL(10,2),
    SALESTATE VARCHAR(20),
    SHIPPRICE DECIMAL(10,2),
    FRAMEPRICE DECIMAL(10,2),
    COMPONENTLIST INT,
    FOREIGN KEY (MODELTYPE) REFERENCES Modeltype(MODELTYPE),
    FOREIGN KEY (PAINTID) REFERENCES Paint(PAINTID),
    FOREIGN KEY (LETTERSTYLEID) REFERENCES Letterstyle(LETTERSTYLE)
);

CREATE TABLE Bikeparts (
    SERIALNUMBER INT,
    COMPONENTID INT,
    SUBSTITUTEID INT,
    LOCATION VARCHAR(50),
    QUANTITY INT,
    DATEINSTALLED DATE,
    EMPLOYEEID INT,
    PRIMARY KEY (SERIALNUMBER, COMPONENTID),
    FOREIGN KEY (SERIALNUMBER) REFERENCES Bicycle(SERIALNUMBER),
    FOREIGN KEY (COMPONENTID) REFERENCES Component(COMPONENTID)
);


CREATE TABLE Biketubes (
    SERIALNUMBER INT NOT NULL,
    TUBEID INT NOT NULL,
    TUBENAME VARCHAR(50) NOT NULL,
    LENGTH DECIMAL(10,2),
    PRIMARY KEY (SERIALNUMBER, TUBENAME),
    FOREIGN KEY (SERIALNUMBER) REFERENCES Bicycle(SERIALNUMBER),
    FOREIGN KEY (TUBEID) REFERENCES Tubematerial(TUBEID)
);
