use bikeshop;

DROP TABLE IF EXISTS city, customer, employee, customertransaction;

CREATE TABLE CITY 
(
    CITYID INT PRIMARY KEY,
    ZIPCODE VARCHAR(50),
    CITY VARCHAR(50), 
    STATE VARCHAR(50),
    AREACODE VARCHAR(50),
    POPULATION1990 INT DEFAULT 0,
    POPULATION1980 INT DEFAULT 0,
    COUNTRY VARCHAR(50),
    LATITUDE DECIMAL DEFAULT null, 
    LONGITUDE DECIMAL DEFAULT null,
    POPULATIONCDF INT DEFAULT 0
);

 CREATE TABLE CUSTOMER 
 ( 
      CUSTOMERID INT PRIMARY KEY, 
	  PHONE VARCHAR(50), 
	  FIRSTNAME VARCHAR(50), 
	  LASTNAME VARCHAR(50), 
	  ADDRESS VARCHAR(50), 
	  ZIPCODE VARCHAR(50), 
	  CITYID INT DEFAULT 0, 
	  BALANCEDUE DECIMAL(38,4) DEFAULT 0,
      
      CONSTRAINT foreign key (CityID) REFERENCES City(CityID)
 );

 CREATE TABLE EMPLOYEE
(
    EMPLOYEEID INT PRIMARY KEY,
    TAXPAYERID VARCHAR(50),
    LASTNAME VARCHAR(50),
    FIRSTNAME VARCHAR(50),
    HOMEPHONE VARCHAR(50),
    ADDRESS VARCHAR(50), 
    ZIPCODE VARCHAR(50),
    CITYID INT DEFAULT 0,
    DATEHIRED DATETIME DEFAULT null,
    DATERELEASED DATETIME DEFAULT null,
    CURRENTMANAGER INT DEFAULT 0,
    SALARYGRADE INT DEFAULT 0,
    SALARY DECIMAL(38,4) DEFAULT 0,
    TITLE VARCHAR(100),
    WORKAREA VARCHAR(50),
    
    CONSTRAINT FOREIGN KEY (CityID) REFERENCES City(CityID)
);

CREATE TABLE CUSTOMERTRANSACTION
(
    CUSTOMERID INT NOT NULL,
    TRANSACTIONDATE DATETIME NOT NULL,
    EMPLOYEEID INT, 
    AMOUNT DECIMAL(38,4) DEFAULT 0,
    DESCRIPTION VARCHAR(250),
    REFERENCE INT DEFAULT 0,
    
    CONSTRAINT PRIMARY KEY (CustomerID, TransactionDate),
    constraint foreign key (CustomerID) references Customer(CustomerID),
    constraint foreign key (EmployeeID) references Employee(EmployeeID)
);


